[build]
publish = "."
command = "echo 'No build command needed for static site'"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

    [[functions]]
  path = "/keep-alive"
  function = "keep-alive"
  schedule = "@daily"
  